name: Build Docker Image
on:
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      packages: write
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - uses: dorny/paths-filter@v3
          id: filter
          with:
            filters: |
              src:
              - 'scripts/**'
              - '.github/**'
        - name: Log into registry ghcr.io
          if: (github.event_name != 'pull_request' && steps.filter.outputs.src == 'true') || startsWith(github.event.ref, 'refs/tags/v')
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract Docker metadata
          if: (github.event_name != 'pull_request' && steps.filter.outputs.src == 'true') || startsWith(github.event.ref, 'refs/tags/v')
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ghcr.io/yefori-go/milkv_duos_debian_builder

        - name: Build and push Docker image
          if: (github.event_name != 'pull_request' && steps.filter.outputs.src == 'true') || startsWith(github.event.ref, 'refs/tags/v')
          id: build-and-push
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./debian/Dockerfile
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
        - name: pause
          if: (github.event_name != 'pull_request' && steps.filter.outputs.src == 'true') || startsWith(github.event.ref, 'refs/tags/v')
          run: sleep 30