name: Build DuoS Debian SD Image
on:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Get Into Repo
        uses: actions/checkout@v4
      - name: Build Image
        uses: addnab/docker-run-action@v3
        with:
            image: ghcr.io/yefori-go/milkv_duos_debian_builder:main
            options: --privileged -e BOARD=milkv-duos-sd -e CONFIG=cv1813h_milkv_duos_sd -e ROOTPW=milkv -v ${{ github.workspace }}/debian:/build -v ${{ github.workspace }}/out:/duo-buildroot-sdk/install
            run: |
              bash /build/build.sh
              chmod 777 /duo-buildroot-sdk/install
              chmod 777 /duo-buildroot-sdk/install/soc_cv1813h_milkv_duos_sd
              chmod 777 /duo-buildroot-sdk/install/soc_cv1813h_milkv_duos_sd/*.img
      - name: Pack Image
        run: |
          cd out/
          ls -lah
          IMAGE=$(find . -type f -name "*.img" | head -n 1)
          if [[ -n "$IMAGE" ]]; then
            gzip "$IMAGE"
            echo "PACKAGE=${{ github.workspace }}/out/$(basename "$IMAGE").gz" >> $GITHUB_ENV
          else
            echo "No image found."
            exit 1
          fi
      - name: Upload Image
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: image-files
          path: ${{env.PACKAGE}}